# Generated by Django 5.2.11 on 2026-03-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('vehicle', 'Heavy Equipment Vehicle'), ('track', 'Track'), ('operator', 'Operator')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('identifier', models.CharField(blank=True, help_text='Unit number, badge ID, or track ID', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cal.asset'),
        ),
    ]
