# Generated by Django 5.2.11 on 2026-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_event_created_by_event_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='asset',
        ),
        migrations.AddField(
            model_name='event',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='events', to='cal.asset'),
        ),
    ]
