# Generated by Django 5.2.11 on 2026-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_event_created_at_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
