# Generated by Django 5.2.11 on 2026-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_remove_asset_identifier_unique_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_active',
        ),
    ]
