# Generated by Django 5.2.11 on 2026-03-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_asset_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent track (only for subtracks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtracks', to='cal.asset'),
        ),
    ]
