# Generated by Django 5.2.11 on 2026-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_event_actual_start_actual_end'),
        ('cal', '0010_subtrack_cascade_delete'),
    ]

    operations = [
    ]
