# Generated by Django 5.2.11 on 2026-03-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_merge_20260318_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_top_level_asset_name'),
        ),
    ]
