# Generated by Django 5.2.11 on 2026-03-23 16:45

from django.db import migrations, models

PALETTE = [
    '#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#ef4444', '#06b6d4',
    '#ec4899', '#84cc16', '#f97316', '#6366f1', '#14b8a6', '#e11d48',
    '#0ea5e9', '#7c3aed', '#a3a3a3', '#059669',
]


def assign_initial_colors(apps, schema_editor):
    Asset = apps.get_model('cal', 'Asset')
    tracks = list(Asset.objects.filter(asset_type='track').order_by('pk'))
    for i, track in enumerate(tracks):
        track.color = PALETTE[i % len(PALETTE)]
        track.save(update_fields=['color'])


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_scoped_asset_name_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color for this track (e.g. #3b82f6). Auto-assigned if left blank.', max_length=7),
        ),
        migrations.RunPython(assign_initial_colors, migrations.RunPython.noop),
    ]
