# Generated by Django 5.2.11 on 2026-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='radio_channel',
            field=models.IntegerField(blank=True, choices=[(11, 'Ch 11'), (12, 'Ch 12'), (13, 'Ch 13'), (14, 'Ch 14'), (15, 'Ch 15'), (16, 'Ch 16')], help_text='Radio channel assigned to this track (11–16).', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('track', 'Track'), ('operator', 'Operator')], max_length=20),
        ),
    ]
