# Generated by Django 5.2.11 on 2026-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_asset_radio_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='radio_channel',
            field=models.IntegerField(blank=True, choices=[(11, 'Ch 11'), (12, 'Ch 12'), (13, 'Ch 13'), (14, 'Ch 14'), (15, 'Ch 15'), (16, 'Ch 16')], default=None, help_text='Override radio channel for this event (11–16). Leave blank to use the track default.', null=True),
        ),
    ]
