# Generated by Django 5.2.11 on 2026-03-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_impromptu',
            field=models.BooleanField(default=False, help_text='Impromptu events have no scheduled time; only actual times.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
