# Generated by Django 5.2.11 on 2026-03-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0018_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='actual_start',
        ),
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this track is currently active/unsafe to approach.'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_impromptu',
            field=models.BooleanField(default=False, help_text='Set automatically for unplanned events created from the dashboard.'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActualTimeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cal.event')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
