# Generated by Django 5.2.11 on 2026-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0019_event_is_impromptu_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='radio_channel',
            field=models.IntegerField(blank=True, choices=[(1, 'Ch 1'), (2, 'Ch 2'), (3, 'Ch 3'), (4, 'Ch 4'), (5, 'Ch 5'), (6, 'Ch 6'), (7, 'Ch 7'), (8, 'Ch 8'), (9, 'Ch 9'), (10, 'Ch 10'), (11, 'Ch 11'), (12, 'Ch 12'), (13, 'Ch 13'), (14, 'Ch 14'), (15, 'Ch 15'), (16, 'Ch 16')], help_text='Radio channel assigned to this track (1–16).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='radio_channel',
            field=models.IntegerField(blank=True, choices=[(1, 'Ch 1'), (2, 'Ch 2'), (3, 'Ch 3'), (4, 'Ch 4'), (5, 'Ch 5'), (6, 'Ch 6'), (7, 'Ch 7'), (8, 'Ch 8'), (9, 'Ch 9'), (10, 'Ch 10'), (11, 'Ch 11'), (12, 'Ch 12'), (13, 'Ch 13'), (14, 'Ch 14'), (15, 'Ch 15'), (16, 'Ch 16')], default=None, help_text='Override radio channel for this event (1–16). Leave blank to use the track default.', null=True),
        ),
    ]
