# Generated by Django 5.2.11 on 2026-04-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0022_expand_radio_channels_1_16'),
    ]

    operations = [
    ]
